baseURL = "https://shuruws.github.io/jots_dots/"
languageCode = "en-us"
title = "My Jots and Dots"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "My Jots and Dots"
description = "A collection of my thoughts, learnings, and adventures in the twenties."
keywords = ["Blog", "ideas", "fun tech"]
author = "Shuru Bonaventure"
DateFormat = "May 2, 2025"
defaultTheme = "auto"
disableThemeToggle = false

[params.homeInfoParams]
Title = "Here is my notepad for random thoughts👋"
Content = """
I got bored working remotely and trying to write for fun. 
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/Shuruws"
