baseURL = "https://shuruws.github.io/jotsNdots/"
languageCode = "en-us"
title = "My Jots and Dots"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "My Jots and Dots"
description = "A collection of my thoughts, learnings, and adventures in the twenties."
keywords = ["Blog", "ideas", "fun tech"]
author = "Shuru"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

[params.homeInfoParams]
Title = "Heyo, welcome to Shuru's jots and dots 👋"
Content = """
Kinda strange to introduce myself, so I'll skip that. You can get to know me by tone and words.

I got dull and a little unmotivated working remotely, so I am trying to write for fun and get sharp again. This is my notepad for a scavenger's hunt for passion.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/Shuruws"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/shuru-wang-0a5101237/"