baseURL = "https://shuruws.github.io/jotsNdots/"
languageCode = "en-us"
title = "My Jots and Dots"
theme = "PaperMod"

enableGitInfo = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "My Jots and Dots"
description = "A collection of my thoughts, learnings, and adventures in the twenties."
keywords = ["Blog", "ideas", "fun tech"]
author = "Shuru"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

[params.homeInfoParams]
Title = "Heyo there, this is Shuru 👋"
Content = """
Kinda strange to introduce myself, so I'll skip that.\n You can get to know me by tone and words.\n
I got dull and a little unmotivated recently, so I am trying to write and get sharp again.\n
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/Shuruws"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/shuru-wang-0a5101237/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true